spring.datasource.url=jdbc:postgresql://localhost:5432/serralyse_db
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true

# Application Info
info.app.name=Serralyse Backend API
info.app.description=Personalized Skincare Analysis Platform
info.app.version=1.0.0
info.app.encoding=UTF-8
info.app.java.version=21.0.10

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
